version: "3.0"
services:
  jenkins:
    image: jenkinsci/blueocean
    privileged: true
    user: root
    ports:
      - 8091:8080
      - 50000:50000
    container_name: jenkins_container
    restart: unless-stopped
    volumes:
     - /data/jenkins-data:/var/jenkins_home
     - /var/run/docker.sock:/var/run/docker.sock
     - /usr/local/bin/docker:/usr/local/bin/docker
